language: python
warnings_are_errors: false
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
script:
    - python -m pytest . --cov=.
after_success:
    - coveralls
