language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
script:
    - python -m pytest pychemkin/ --cov=pychemkin/
after_success:
    - coveralls
